Models/Home/Functions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MutualAid.Models.Home
{
    public class Functions
    {
        public static string Encrypt(string password)
        {
            var salt = BCrypt.Net.BCrypt.GenerateSalt();
            string passwordHash = BCrypt.Net.BCrypt.HashPassword(password, "$2a$10$IKmTt3y83y5doeC/L6JEgu");
            return passwordHash;
        }
    }
}

Models/Home/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MutualAid.Models.Home
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string NewPassword { get; set; }
        public string RepeatPassword { get; set; }
    }
    public class RegisterViewModel
    {
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string RepeatPassword { get; set; }
        public string Email { get; set; }
        public Role Role { get; set; }
        public bool Active { get; set; }
    }
    public enum Role
    {
        Admin,
        Member
    }
    public class MailModel
    {
        public string From
        {
            get;
            set;
        }
        public string To
        {
            get;
            set;
        }
        public string Subject
        {
            get;
            set;
        }
        public string Body
        {
            get;
            set;
        }
    }
}

Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaptchaMvc.HtmlHelpers;
using MutualAid.Models.Transaction;
using System.Data.Entity;

namespace MutualAid.Controllers
{
    public class TransactionController : Controller
    {
       public ActionResult NewDeposit()
        {
            var sessionUser = Session["User"] as SystemUser;
            if (sessionUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(new DepositViewModel());
            }
        }
        [HttpPost]
        public ActionResult NewDeposit(DepositViewModel model)
        {
            var sessionUser = Session["User"] as SystemUser;
            if (sessionUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (this.IsCaptchaValid("Validate your captcha"))
                {
                    using (var db = new MutualAidEntities())
                    {
                        var setup = db.Setups.FirstOrDefault();
                        var check = model.Amount % 1000;
                        if (model.Amount < setup.DepositMin || model.Amount > setup.DepositMax)
                        {
                            ViewBag.Message = "The amount entered should be between Ksh" + setup.DepositMin + " and Ksh. " + setup.DepositMax;
                            return View(model);
                        }
                     
                        else  if (check != 0)
                        {
                            ViewBag.Message = "Your Deposit should be in multiple of thousands i.e , 1000, 2000,5000 e.t.c";
                            return View(model);
                        }
                        else
                        {
                            var depo = new Deposit
                            {
                                Id = Guid.NewGuid(),
                                Amount = model.Amount,
                                DepositType = 0,
                                DateDeposited = DateTime.Now,
                                DepositedBy = sessionUser.Email

                            };
                            db.Deposits.Add(depo);
                            db.SaveChanges();
                            return RedirectToAction("Dashboard", "Home");
                        }
                    }
                       
                }
                else
                {
                    ViewBag.ErrMessage = "Enter the right code";
                    return View(model);
                }
                
            }
        }
        #region withdraw
        public ActionResult Withdraw()
        {
            var sessionUser = Session["User"] as SystemUser;
            if (sessionUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                WithdrawViewModel model = new WithdrawViewModel();
                var deposit = new Deposit();
                var rate = new Rate();
                var principal = new decimal();
                var redepo = new decimal();
                if (sessionUser != null)
                {
                    using (var db = new MutualAidEntities())
                    {
                        deposit = db.Deposits.FirstOrDefault(p => p.DepositedBy == sessionUser.Email);
                      
                        rate = db.Rates.FirstOrDefault();
                        if (deposit != null)
                        {
                            var bonus = (rate.BonusRate / 100) * deposit.Amount;
                            principal = deposit.Amount + bonus;
                            redepo = principal / 2;
                            model.DepositId = deposit.Id;
                        }

                    }
                }
                model.Redeposit = redepo;
                model.Principal = principal;
            
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult Withdraw(WithdrawViewModel model)
        {
            var sessionUser = Session["User"] as SystemUser;
            if (sessionUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                using (var db = new MutualAidEntities())
                {
                    var redepo = model.Principal / 2;
                    var setup = db.Setups.FirstOrDefault();
                    var check = model.Redeposit % 1000;
                    if (model.Redeposit < redepo)
                    {
                        ViewBag.Error = "Redeposit cannot be lower than half the amount withdrawable";
                        return View(model);
                    }
                    
                     else if (model.Redeposit < setup.DepositMin || model.Redeposit > setup.DepositMax)
                    {
                        ViewBag.Message = "The amount entered should not exceeed and Ksh. " + setup.DepositMax;
                        return View(model);
                    }
                    
                    else if (check != 0)
                    {
                        ViewBag.Message = "Your Deposit should be in multiple of thousands i.e , 1000, 2000,5000 e.t.c";
                        return View(model);
                    }
                    else
                    {
                        var withdraw = new Withdraw
                        {
                            Id = Guid.NewGuid(),
                            Amount = model.Principal,
                            DepositId = model.DepositId,
                            MadeBy = sessionUser.Email,
                            DateMade = DateTime.Now,
                            WithdrawStatus = 0
                        };
                        db.Withdraws.Add(withdraw);
                        var depo = new Deposit
                        {
                            Id = Guid.NewGuid(),
                            Amount = model.Redeposit,
                            DepositType = 1,
                            DateDeposited = DateTime.Now,
                            DepositedBy = sessionUser.Email
                        };
                        db.Deposits.Add(depo);
                        db.SaveChanges();
                        return RedirectToAction("Dashboard", "Home");
                    }

                    
                }
            }
        }
        public ActionResult GenerateWithdrawal()
        {
            var sessionUser = Session["User"] as SystemUser;
            if (sessionUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (sessionUser != null && sessionUser.Role == 0)
            {
                return View(new WithdrawViewModel());
            }
            else
            {
                Session["Access"] = "Access Denied";
                return RedirectToAction("Index", "Admin");
            }
        
        }
        [HttpPost]
        public ActionResult GenerateWithdrawal(WithdrawViewModel model)
        {
            var sessionUser = Session["User"] as SystemUser;
            if (sessionUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {

                using (var db = new MutualAidEntities())
                {
                    var adminDepo = model.Amount / 2;
                    var depo = new Deposit
                    {
                        Id = Guid.NewGuid(),
                        Amount = adminDepo,
                        DepositType = 0,
                        DateDeposited = DateTime.Now,
                        DepositedBy = sessionUser.Email,
                        IsPaid = true,
                        IsMature = true,
                    };
                    db.Deposits.Add(depo);
                    var withdraw = new Withdraw
                    {
                        Id = Guid.NewGuid(),
                        Amount = model.Amount,
                        DepositId = depo.Id,
                        MadeBy = sessionUser.Email,
                        DateMade = DateTime.Now,
                        WithdrawStatus = 0
                    };
                    db.Withdraws.Add(withdraw);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Admin");
                }
            }
        }
        #endregion
        #region match pay and receive
        public ActionResult Withdrawals()
        {
            var sessionUser = Session["User"] as SystemUser;
            if (sessionUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                using (var db = new MutualAidEntities())
                {
                    var withdrawals = db.Withdraws.Where(p => p.WithdrawStatus == 0).OrderBy(p=>p.DateMade).ToList();
                    return View(withdrawals);
                }
            }
        }
        public ActionResult MatchRequest(Guid id)
        {
            var sessionUser = Session["User"] as SystemUser;
            if (sessionUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                MatchViewModel model = new MatchViewModel();
                model.DepositModels = new List<DepositModel>();
                using (var db = new MutualAidEntities())
                {
                    var withdrawal = db.Withdraws.FirstOrDefault(p => p.Id == id);
                    model.WithdrawalId = id;

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/ChangePassword.cshtml
@model MutualAid.Models.Home.LoginViewModel

@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<div class="page-inner">
    <!--================================-->
    <!-- Main Wrapper Start -->
    <!--================================-->
    <div id="main-wrapper">
        <!--================================-->
        <!-- Breadcrumb Start -->
        <!--================================-->
        <div class="pageheader pd-t-25 pd-b-35">
            <div class="pd-t-5 pd-b-5">
                <h1 class="pd-0 mg-0 tx-20 text-overflow">Mutual Aid</h1>
            </div>
            <div class="breadcrumb pd-0 mg-0">
                <a class="breadcrumb-item" href="index.html"><i class="icon ion-ios-home-outline"></i> Home</a>
                <span class="breadcrumb-item active">Change Password</span>
            </div>
        </div>
        <!--/ Breadcrumb End -->
        <div class="row row-xs clearfix">
            <!--================================-->
            <!-- Basic Form Start -->
            <!--================================-->
            <div class="col-md-12 col-lg-12">
                <div class="card mg-b-20">
                    <div class="card-header">
                        <h4 class="card-header-title">
                            Change Password
                        </h4>
                        @if (ViewBag.Message != null)
                        {
                            <p style="color:red">@ViewBag.Message</p>
                        }
                        @if (ViewBag.Success != null)
                        {
                            <p style="color:green">@ViewBag.Success</p>
                        }
                    </div>
                    <div class="card-body collapse show" id="collapse1">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.Email)

                        <div class="form-horizontal">

                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group row">
                                <label>Email Address</label>
                                <div class="col-sm-10">
                                    @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @type = "email" } })

                                </div>
                            </div>
                            <div class="form-group row">
                                <label>Current Password</label>
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control form-control-sm", @placeholder = "password", @type = "password" } })

                                </div>
                            </div>

                            <div class="form-group row">
                                <label>New Password</label>
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control form-control-sm", @placeholder = "password", @type = "password" } })

                                </div>
                            </div>
                            <div class="form-group row">
                                <label>Confirm Password</label>
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.RepeatPassword, new { htmlAttributes = new { @class = "form-control form-control-sm", @placeholder = "password", @type = "password" } })

                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save Changes" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                        }

                    </div>
                </div>
            </div>
            <!--/ Basic Form End -->

        </div>
    </div>
    <!--/ Main Wrapper End -->
</div>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Admin.cshtml";
    var sessionUser = Session["User"] as SystemUser;
    List<Deposit> deposits = new List<Deposit>();
    var myDeposit = new Deposit();
    var UnWithdrawn = new Deposit();
    var rate = new Rate();
    MutualAid.Models.Transaction.PayViewModel Payto = new MutualAid.Models.Transaction.PayViewModel();
    MutualAid.Models.Transaction.PayViewModel ReceiveFrom = new MutualAid.Models.Transaction.PayViewModel();
    if (sessionUser != null)
    {
        using (var db = new MutualAidEntities())
        {
            deposits = db.Deposits.Where(p => p.DepositedBy == sessionUser.Email && p.IsWithdrawn == false).OrderBy(p => p.DateDeposited).ToList();
            myDeposit = db.Deposits.FirstOrDefault(p => p.DepositedBy == sessionUser.Email && p.DepositType == 0);
            UnWithdrawn = db.Deposits.FirstOrDefault(p => p.DepositedBy == sessionUser.Email && p.IsPaid == true && p.IsMature == true && p.IsWithdrawn == false);
            rate = db.Rates.FirstOrDefault();

        }

        Payto.MatchViewModels = new List<MutualAid.Models.Transaction.MatchViewModel>();
        using (var db = new MutualAidEntities())
        {
            var pendings = db.PayReceives.Where(p => p.IsPayed == false && p.PayedBy == sessionUser.Email).ToList();
            foreach (var item in pendings)
            {
                var due = new MutualAid.Models.Transaction.MatchViewModel
                {
                    Id = item.Id,
                    Amount = item.Amount,
                    DepositId = item.DepositId,
                    WithdrawalId = item.WithdrawalId,
                    ReceivedBy = item.ReceivedBy,
                    DueDate = item.ExpectedPaymentDate

                };
                Payto.MatchViewModels.Add(due);
            }

        }
        ReceiveFrom.MatchViewModels = new List<MutualAid.Models.Transaction.MatchViewModel>();
        using (var db = new MutualAidEntities())
        {
            var pendings = db.PayReceives.Where(p => p.IsPayed == false && p.ReceivedBy == sessionUser.Email).ToList();
            foreach (var item in pendings)
            {
                var due = new MutualAid.Models.Transaction.MatchViewModel
                {
                    Id = item.Id,
                    Amount = item.Amount,
                    DepositId = item.DepositId,
                    WithdrawalId = item.WithdrawalId,
                    PayedBy = item.PayedBy,
                    DueDate = item.ExpectedPaymentDate

                };
                ReceiveFrom.MatchViewModels.Add(due);
            }

        }
    }


}

<div class="page-inner">
    <!-- Main Wrapper -->
    <div id="main-wrapper">
        <!--================================-->
        <!-- Breadcrumb Start -->
        <!--================================-->
        <div class="pageheader pd-t-25 pd-b-35">
            <div class="pd-t-5 pd-b-5">
                <h1 class="pd-0 mg-0 tx-20">Mutual Aid</h1>
            </div>
            <div class="breadcrumb pd-0 mg-0">
                <a class="breadcrumb-item" href="index.html"><i class="fa fa-home"></i> Home</a>
                <a class="breadcrumb-item" href="">Dashboard</a>
                <span class="breadcrumb-item active">Mutual Aid</span>
            </div>
        </div>
        <!--/ Breadcrumb End -->
        <!--================================-->
        <div class="row clearfix">
            <div class="col-lg-12 col-xl-6">
                <div class="row row-xs">
                    <div class="col-sm-12">
                        <div class="card mg-b-20">
                            <div class="card-body bg-warning">
                                <div class="media d-inline-flex">
                                    <div>
                                        <span class="tx-uppercase tx-10 mg-b-10">DEPOSIT</span>
                                        @if (myDeposit != null)
                                        {
                                            <h2 class="tx-20 tx-sm-18 tx-md-24 mb-0 mt-2 mt-sm-0 tx-normal tx-rubik tx-white"> <a href="#" class="btn btn-lg btn-primary" id="sweetalert-example-1"><i class="mdi mdi-file-pdf"></i>CLICK HERE</a></h2>
                                        }
                                        else
                                        {
                                            <h2 class="tx-20 tx-sm-18 tx-md-24 mb-0 mt-2 mt-sm-0 tx-normal tx-rubik tx-white"> <a href="@Url.Action("NewDeposit","Transaction")" class="btn btn-sm btn-light mg-t-5"><i class="mdi mdi-file-pdf"></i>CLICK HERE</a></h2>

                                        }

                                    </div>
                                </div>
                                <div class="clearfix">

                                    <span class="float-right">
                                        <i class="ion-android-arrow-up mr-1 tx-success"></i><span class="tx-dark"></span><span class="small mg-b-0"></span>
                                    </span>
                                </div>
                                <div class="progress ht-3 op-5">
                                    <div class="progress-bar bg-primary wd-100p" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="card mg-b-20">
                            <div class="card-body bg-dark active">
                                <div class="media d-inline-flex">
                                    <div>
                                        <span class="tx-uppercase tx-10 mg-b-10">WITHDRAW</span>
                                        @if (UnWithdrawn == null)
                                        {
                                            <h2 class="tx-20 tx-sm-18 tx-md-24 mb-0 mt-2 mt-sm-0 tx-normal tx-rubik tx-white"> <a href="#" class="btn btn-lg btn-primary" id="sweetalert-example-8"><i class="mdi mdi-file-pdf"></i>CLICK HERE</a></h2>
                                        }
                                        else
                                        {
                                            <h2 class="tx-20 tx-sm-18 tx-md-24 mb-0 mt-2 mt-sm-0 tx-normal tx-rubik tx-white"> <a href="@Url.Action("Withdraw","Transaction")" class="btn btn-sm btn-light mg-t-5"><i class="mdi mdi-file-pdf"></i> CLICK HERE</a> </h2>
                                        }

                                    </div>
                                </div>
                                <div class="clearfix">

                                </div>
                                <div class="progress ht-3 op-5">
                                    <div class="progress-bar bg-warning wd-100p" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if (deposits == null)
                    {
                        <div class="col-md-12">
                            <div class="card mg-b-20">
                                <div class="card card-body">
                                    <div class="d-flex">
                                        <span class="wd-80 ht-80 card-icon-primary d-flex align-items-center justify-content-center rounded hidden-xs"><i class="ion-ios-speedometer-outline tx-50"></i></span>
                                        <div class="mg-l-0 mg-md-l-20">
                                            <div class="media d-inline-flex">
                                                <div>
                                                    <span class="tx-uppercase tx-10 mg-b-10">Amount</span>

                                                    <h2 class="tx-20 tx-sm-18 tx-md-24 mb-0 mt-2 mt-sm-0 tx-normal tx-rubik tx-dark">KSH.<span class="counter">0.00</span></h2>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                        foreach (var item in deposits)
                        {
                            <div class="col-md-12">
                                <div class="card mg-b-20">
                                    <div class="card card-body">
                                        <div class="d-flex">
                                            <span class="wd-80 ht-80 card-icon-primary d-flex align-items-center justify-content-center rounded hidden-xs"><i class="ion-ios-speedometer-outline tx-50"></i></span>
                                            <div class="mg-l-0 mg-md-l-20">
                                                <div class="media d-inline-flex">
                                                    <div>
                                                        <span class="tx-uppercase tx-10 mg-b-10">Amount</span>
                                                        @{
                                                            var bonus = (rate.BonusRate / 100) * item.Amount;
                                                            var principal = item.Amount + bonus;
                                                            if (item.IsPaid == false)
                                                            {
                                                                <h2 class="tx-20 tx-sm-18 tx-md-24 mb-0 mt-2 mt-sm-0 tx-normal tx-rubik tx-dark">KSH.<span class="counter">@principal.ToString("#,##0.00")</span></h2>
                                                                <h3>Unpaid Bonus</h3>
                                                            }
                                                            else if (item.IsPaid == true && item.IsMature == false)
                                                            {

                                                                <h2 class="tx-20 tx-sm-18 tx-md-24 mb-0 mt-2 mt-sm-0 tx-normal tx-rubik tx-dark">KSH.<span class="counter">@principal.ToString("#,##0.00")</span></h2>
                                                                <h3>Paid Waiting Maturity</h3>
                                                                if (item.MatureBy != null)
                                                                {
                                                                    string sqlFormattedDate = item.MatureBy.HasValue 
                                                                    ? item.MatureBy.Value.ToString("dd-MM-yyyy")
                                                                    : "<not available>";
                                                                    DateTime daysleft = item.MatureBy.Value;
                                                                    DateTime startdate = DateTime.Now;
                                                                    TimeSpan t = daysleft - startdate;
                                                                    string countdown = string.Format("{0}hrs", t.TotalHours.ToString("0.0"));

                                                                    <h4>Matures In <b> @countdown</b> </h4>
                                                                }

                                                            }
                                                            else if (item.IsMature == true)
                                                            {

                                                             
                                                                <h2 class="tx-20 tx-sm-18 tx-md-24 mb-0 mt-2 mt-sm-0 tx-normal tx-rubik tx-dark">KSH.<span class="counter">@principal.ToString("#,##0.00")</span></h2>
                                                                <h3>Deposit Mature, Withdraw </h3>
                                                            }
                                                        }



                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    }

                    @if (Payto.MatchViewModels.Count > 0)
                    {
                        { Html.RenderAction("PayToDashboard", "Home"); }


                    }
                    @if (ReceiveFrom.MatchViewModels.Count > 0)
                    {
                        { Html.RenderAction("ReceiveFromDash", "Home"); }

                    }

                </div>
                @*Payto*@
         
            </div>

        </div>





    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Mutual Aid";
}

<section class="ht-100v d-flex home-intro">
    <div class="card mx-auto text-center bd-transparent bg-transparent mg-t-50 align-self-top">
        <div class="bd-transparent " style="">
            <img src="~/Content/assets/images/mutual_aid.png" />
            @*<h1 class="tx-dark">Mutual Aid</h1>
            <h3 class="tx-dark">Home of Financial Freedom</h3>*@
            <p class="tx-15 wd-50p mx-auto text-white">We are a community of ordinary people who believe in coming together to soley help one another to achieve our goals and dreams. In the spirit of giving, mutual aid enables us receive double what we have given to others. When we come together great things happen.</p>
            <div class="mg-t-15">
                
                <a href="@Url.Action("Signin","Home")" class="btn btn-primary btn-lg  mg-y-20">LOGIN</a>
                <a href="@Url.Action("Signup","Home")" class="btn btn-dark active btn-lg  mg-y-20">REGISTER</a>
            </div>
        </div>
    </div>

</section>